name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  server-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        go: ['1.18','1.18.1']
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: go mod package cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}

      - name: Build
        run: |
          pwd
          go build -v ./...



